<a href="https://colab.research.google.com/github/MrNeilMehta/NumPy_Tutorial/blob/main/NumPy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

The Basics

In [3]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:

# Get Dimension
a.ndim

In [ ]:
# Get Shape
b.shape

In [ ]:
# Get Type
a.dtype

In [ ]:
# Get Size
a.itemsize

In [ ]:
# Get total size
a.nbytes

In [ ]:
# Get number of elements
a.size

Accessing/Changing specific elements, rows, columns, etc

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

In [ ]:
# Get a specific element [r, c]
a[1, 5]

In [ ]:
# Get a specific row 
a[0, :]

In [ ]:
# Get a specific column
a[:, 2]

In [ ]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

In [ ]:
a[1,5] = 20

In [ ]:
a[:,2] = [1,2]
print(a)

In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

In [ ]:
# Get specific element (work outside in)
b[0,1,1]

In [ ]:
# replace 
b[:,1,:] = [[9,9,9],[8,8]]

In [ ]:
b

Initializing Different Types of Arrays

In [ ]:
# All 0s matrix
np.zeros((2,3))

In [ ]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

In [ ]:
# Any other number
np.full((2,2), 99)

In [ ]:
# Any other number (full_like)
np.full_like(a, 4)

In [ ]:
# Random decimal numbers
np.random.rand(4,2)

In [ ]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

In [ ]:
# The identity matrix
np.identity(5)

In [ ]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

In [ ]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

Mathematics

In [ ]:
a = np.array([1,2,3,4])
print(a)

In [ ]:
a + 2

In [ ]:
a - 2

In [ ]:
a * 2

In [ ]:
a / 2

In [ ]:
b = np.array([1,0,1,0])
a + b

In [ ]:
a ** 2

In [ ]:
# Take the sin
np.cos(a)

Linear Algebra

In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

In [ ]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

Statstics

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

In [ ]:
np.min(stats)

In [ ]:
np.max(stats, axis=1)

In [ ]:
np.sum(stats, axis=0)

Reorganising Arrays

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,3))
print(after)

In [ ]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

In [ ]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

Misc

Load Data from File

In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

Boolean Masking and Advanced Indexing

In [ ]:
(~((filedata > 50) & (filedata < 100)))